openapi: 3.0.0
info:
  title: Fruitables API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8000/api/v1
    description: Local server
  - url: http://example.com
    description: Optional server description, e.g. Internal staging server for testing
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []      
paths:
  /users/ragister:
    post:
      summary: user ragistration.
      description: Optional extended description in CommonMark or HTML.
      tags : 
        - users
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                avtar:
                  type: string
                  format: binary  
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/login:
    post:
      summary: user login.
      description: Optional extended description in CommonMark or HTML.
      tags : 
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/logout:
    post:
      summary: user logout.
      description: Optional extended description in CommonMark or HTML.
      tags : 
        - users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _id:
                  type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/newtoken:
    post:
      summary: user newtoken.
      description: Optional extended description in CommonMark or HTML.
      tags : 
        - users
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string                                
  /users/googleLogin:
    get:
      summary: user googleLogin.
      description: Optional extended description in CommonMark or HTML.
      tags : 
        - users
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string     
  /categories/categories-list:
    get:
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: page no 
        - in: query
          name: pageSize
          schema:
            type: integer
          description: page size
      summary: user categories list.
      description: Optional extended description in CommonMark or HTML.
      tags : 
        - Categories
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string       
  /categories/categories-update/{category_id}:
    put:
      parameters:
        - in: path
          name: category_id
          required: true
          schema:
            type: string
            minimum: 1
          required: true
          description: category id
      summary: user categories update.
      description: Optional extended description in CommonMark or HTML.
      tags : 
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string 
                discription:
                  type: string    
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string                            
                                             

