export const ADD_FACILITES = "ADD_FACILITES"

export const DELETE_FACILITES = "DELETE_FACILITES"

export const UPDATE_FACILITES = "UPDATE_FACILITES"

export const GET_FACILITES = "GET_FACILITES"




export const GET_SHOPDATA = "GET_SHOPDATA"



export const ADD_REVIEWE = "ADD_REVIEWE"

export const GET_REVIEWE = "GET_REVIEWE"

export const DELETE_REVIEWE = "DELETE_REVIEWE"

export const UPDATE_REVIEWE = "UPDATE_REVIEWE"


export const GET_CART = "GET_CART"

export const ADD_CATEGORY = "ADD_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const GET_CATEGORY = "GET_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"


export const GET_PRODUCTS = "GET_PRODUCTS"
export const ADD_PRODUCTS = "ADD_PRODUCTS"
export const DELETE_PRODUCTS = "DELETE_PRODUCTS"
export const EDIT_PRODUCTS = "EDIT_PRODUCTS"
export const LOADING_PRODUCTS = "LOADING_PRODUCTS"
export const ERROR_PRODUCTS = "ERROR_PRODUCTS"



export const LOADING_VARIANTS = "LOADING_VARIANTS"
export const ERROR_VARIANTS = "ERROR_VARIANTS"
export const GET_VARIANTS = "GET_VARIANTS"
export const ADD_VARIANTS = "ADD_VARIANTS"
export const DELETE_VARIANTS = "DELETE_VARIANTS"
export const EDIT_VARIANTS = "EDIT_VARIANTS"



export const GET_SALESPEOPLE = "GET_SALESPEOPLE"
export const ADD_SALESPEOPLE = "ADD_SALESPEOPLE"
export const DELETE_SALESPEOPLE = "DELETE_SALESPEOPLE"
export const EDIT_SALESPEOPLE = "EDIT_SALESPEOPLE"